### ISSUE TITLE
Pick t-threshold automatically

### ISSUE THREAD

**Issue by carloscinelli** [nlapier2/mrsensemakr#2]
Pick t-threshold automatically, considering the significance level (alpha), degrees of freedom and the sign of the original estimate (positive or negative).

**Comment by nlapier2** [comment]
https://github.com/carloscinelli/mrsensemakr/commit/3a12fcaa22d2bd3cdb15ab8af65cec342370ca7c#diff-d01e1f5bdcdb8ac8a435f61172871fb7631468754c33160135f9678fb50ae433

**Comment by nlapier2** [comment]
Resolved by commit baf2c46
