### ISSUE TITLE
Make sure alpha from call matches alpha from plot

### ISSUE THREAD

**Issue by carloscinelli** [nlapier2/mrsensemakr#3]

**Comment by nlapier2** [comment]
see: https://github.com/carloscinelli/mrsensemakr/commit/b97a620e79b2ab720bd9dfa5d4905d9f03b286f1#diff-d01e1f5bdcdb8ac8a435f61172871fb7631468754c33160135f9678fb50ae433

**Comment by nlapier2** [comment]
Resolved by commit baf2c46
